# CI setup based on https://gitlab.gnome.org/GNOME/librsvg/blob/master/.gitlab-ci.yml

variables:
  AMD64_DEBIAN_TESTING: debian:testing
  AMD64_UBUNTU_BIONIC: ubuntu:bionic
  AMD64_FEDORA_LATEST: fedora:latest
  AMD64_FEDORA_RAWHIDE: fedora:rawhide
  AMD64_OPENSUSE_LEAP: opensuse/leap
  AMD64_OPENSUSE_TUMBLEWEED: opensuse/tumbleweed

stages:
  - test

.test_bzip2_template: &bzip2_test
  script:
    - mkdir builddir && cd builddir
    - ../autogen.sh
    - make
    - make check
  after_script:
    - cp builddir/config.status builddir/config.log .
    - rm -rf builddir
  artifacts:
    paths:
      - 'config.status'
      - 'config.log'

.meson_bzip2_template_meson: &bzip2_meson
  script:
    - meson builddir
    - ninja -C builddir
    - ninja -C builddir test
  after_script:
    - cp builddir/meson-logs/meson-log.txt .
    - rm -rf builddir
  artifacts:
    paths:
      - 'meson-log.txt'
  
debian:testing:autotools:
  image: $AMD64_DEBIAN_TESTING
  stage: test
  before_script:
    - apt update -y
    - apt install -y gcc make automake libtool
  <<: *bzip2_test

debian:testing:meson:
  image: $AMD64_DEBIAN_TESTING
  stage: test
  before_script:
    - apt update -y
    - apt install -y gcc meson
  <<: *bzip2_meson

ubuntu:bionic:autotools:
  image: $AMD64_UBUNTU_BIONIC
  stage: test
  before_script:
    - apt update -y
    - apt install -y gcc make automake libtool
  <<: *bzip2_test

ubuntu:bionic:meson:
  image: $AMD64_UBUNTU_BIONIC
  stage: test
  before_script:
    - apt update -y
    - apt install -y gcc python3-pip ninja-build
    - pip3 install meson
  <<: *bzip2_meson

fedora:latest:autotools:
  image: $AMD64_FEDORA_LATEST
  stage: test
  before_script:
    - dnf install -y gcc make automake libtool
  <<: *bzip2_test

fedora:latest:meson:
  image: $AMD64_FEDORA_LATEST
  stage: test
  before_script:
    - dnf install -y gcc meson
  <<: *bzip2_meson

fedora:rawhide:autotools:
  image: $AMD64_FEDORA_RAWHIDE
  stage: test
  before_script:
    - dnf install -y gcc make automake libtool
  allow_failure: true
  <<: *bzip2_test

fedora:rawhide:meson:
  image: $AMD64_FEDORA_RAWHIDE
  stage: test
  before_script:
    - dnf install -y gcc meson
  allow_failure: true
  <<: *bzip2_meson

opensuse/leap:autotools:
  image: $AMD64_OPENSUSE_LEAP
  stage: test
  before_script:
    - zypper install -y gcc make automake libtool
  <<: *bzip2_test

opensuse/leap:meson:
  image: $AMD64_OPENSUSE_LEAP
  stage: test
  before_script:
    - zypper install -y gcc ninja python3-pip
    - pip3 install meson
  <<: *bzip2_meson

opensuse/tumbleweed:autotools:
  image: $AMD64_OPENSUSE_TUMBLEWEED
  stage: test
  before_script:
    - zypper install -y gcc make automake libtool
  <<: *bzip2_test

opensuse/tumbleweed:meson:
  image: $AMD64_OPENSUSE_TUMBLEWEED
  stage: test
  before_script:
    - zypper install -y gcc meson
  <<: *bzip2_meson
