# CI setup based on https://gitlab.gnome.org/GNOME/librsvg/blob/master/.gitlab-ci.yml

variables:
  AMD64_DEBIAN_TESTING: debian:testing
  AMD64_UBUNTU_BIONIC: ubuntu:bionic
  AMD64_FEDORA_LATEST: 'registry.fedoraproject.org/fedora:30'
  AMD64_FEDORA_RAWHIDE: 'registry.fedoraproject.org/fedora:rawhide'
  AMD64_OPENSUSE_LEAP: opensuse/leap
  AMD64_OPENSUSE_TUMBLEWEED: opensuse/tumbleweed

stages:
  - test

.test:
  stage: test
  script:
    - mkdir builddir && cd builddir
    - ../autogen.sh
    - make
    - make check
  after_script:
    - cp builddir/config.status builddir/config.log .
    - rm -rf builddir
  artifacts:
    paths:
      - 'config.status'
      - 'config.log'
  
debian:testing:
  extends: '.test'
  image: $AMD64_DEBIAN_TESTING
  before_script:
    - apt update -y
    - apt install -y gcc make automake libtool

ubuntu:bionic:
  extends: '.test'
  image: $AMD64_UBUNTU_BIONIC
  before_script:
    - apt update -y
    - apt install -y gcc make automake libtool

fedora:latest:
  extends: '.test'
  image: $AMD64_FEDORA_LATEST
  before_script:
    - dnf install -y gcc make automake libtool

fedora:rawhide:
  extends: '.test'
  image: $AMD64_FEDORA_RAWHIDE
  before_script:
    - dnf install -y gcc make automake libtool
  allow_failure: true

opensuse/leap:
  extends: '.test'
  image: $AMD64_OPENSUSE_LEAP
  before_script:
    - zypper install -y gcc make automake libtool

opensuse/tumbleweed:
  extends: '.test'
  image: $AMD64_OPENSUSE_TUMBLEWEED
  before_script:
    - zypper install -y gcc make automake libtool
